/**
 * 頁面快取偵測 —— 解「改了卻沒變」的快取時間差誤會。
 *
 * 2026-08-13 實案：用戶把 Meta 描述 84 字改成 72 字，重掃仍測到 84 字 → 以為 AI 沒真的改。
 * 真相：LiteSpeed 還在供應 00:52 的舊快取頁。快取外掛會在 HTML 留註記（含生成時間），
 * 偵測它、告訴用戶「這是 X 小時前的快取版，剛改過請先清快取再掃」，誤會從源頭消掉。
 *
 * 誠實立場：掃描讀快取版是「對的」——AI 爬蟲拿到的也是這份快取；問題只在改完後的時間差。
 * ⚠️ 延續性（AGENTS.md §0.1）：現行產品與改版共用這支，改版、大改版都要沿用。
 */

// 各快取外掛的 HTML 註記指紋（timeRe 抓生成時間；抓不到時間也回報外掛名，仍有提示價值）
const CACHE_SIGNATURES = [
  { plugin: 'LiteSpeed 快取', re: /Page cached by LiteSpeed Cache/i, timeRe: /Page cached by LiteSpeed Cache[^>]*? on (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})/i },
  { plugin: 'WP Super Cache', re: /Cached page generated by WP-Super-Cache/i, timeRe: /WP-Super-Cache on (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})/i },
  { plugin: 'W3 Total Cache', re: /by W3 Total Cache/i, timeRe: /@ (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) by W3 Total Cache/i },
  { plugin: 'WP Rocket', re: /This website is like a Rocket/i, timeRe: null },
  { plugin: 'WP Fastest Cache', re: /WP Fastest Cache file was created/i, timeRe: null },
]

/**
 * 從頁面 HTML 找快取外掛註記。
 * @returns {{ plugin, cachedAt: Date|null, ageMinutes: number|null }|null} 沒偵測到快取回 null
 * 註：外掛寫的是「伺服器當地時間」（無時區資訊），這裡以瀏覽器時區解讀——台灣站台通常一致；
 *     若算出負值（伺服器時區超前）視為剛生成、回 ageMinutes 0。
 */
export function detectCacheInfo(html) {
  if (!html) return null
  for (const sig of CACHE_SIGNATURES) {
    if (!sig.re.test(html)) continue
    let cachedAt = null
    let ageMinutes = null
    const m = sig.timeRe ? html.match(sig.timeRe) : null
    if (m) {
      const d = new Date(m[1].replace(' ', 'T'))
      if (!Number.isNaN(d.getTime())) {
        cachedAt = d
        ageMinutes = Math.max(0, Math.round((Date.now() - d.getTime()) / 60000))
      }
    }
    return { plugin: sig.plugin, cachedAt, ageMinutes }
  }
  return null
}

/** 把快取年齡轉成好讀字串：42 分鐘前 / 13 小時前 / 3 天前 */
export function describeCacheAge(ageMinutes) {
  if (ageMinutes == null) return null
  if (ageMinutes < 60) return `約 ${ageMinutes} 分鐘前`
  if (ageMinutes < 60 * 24) return `約 ${Math.round(ageMinutes / 60)} 小時前`
  return `約 ${Math.round(ageMinutes / (60 * 24))} 天前`
}
